### ISSUE TITLE
How to complie libdarknet.so?

### ISSUE THREAD

**Issue by cuongdev** [sowson/darknet#17]
I got this error when run darknet.py
`OSError: dlopen(libdarknet.so, 10): image not found`
Please kindly help me.

**Comment by yaoanderson** [comment]
Please use absolute image path, not relative path in configuration :)

**Comment by cuongdev** [comment]
> Please use absolute image path, not relative path in configuration :)

Where is the path of that find? I can’t find it in project when success compiling

**Comment by sowson** [comment]
The "pwd" command can tell you the absolute path where you compiled the darknet..? Can you put command you used to compile?

the relative path is for example:
libdarknet.so
the absolute path is for example:
/Users/piotrsowa/Projects/github/darknet/libdarknet.so

Hope that helps! Thanks!

**Comment by cuongdev** [comment]
> The "pwd" command can tell you the absolute path where you compiled the darknet..? Can you put command you used to compile?
> 
> the relative path is for example:
> libdarknet.so
> the absolute path is for example:
> /Users/piotrsowa/Projects/github/darknet/libdarknet.so
> 
> Hope that helps! Thanks!

I used these command
`git clone https://github.com/sowson/darknet.git
cd darknet; mkdir build; cmake -Bbuild -H.; cd build; make; cd ..; cp build/darknet .; rm -r build`

before running those commands. I ran these commands:
`/usr/bin/ruby -e “$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)”
brew install opencv@2
brew link –force opencv@2
brew install libomp
brew install clblas
brew install clfft
brew install cmake
brew install wget`

Please help me, There's no libdarknet.so in my darknet folder

**Comment by sowson** [comment]
ok so... in the
`mkdir build; cmake -Bbuild -H.; cd build; make; cd ..; cp build/darknet .; rm -r build`
the issue is last command:
`rm -r build`
because in build folder there is darknet binary and your missing lib/file as well...
do please do not remove build, by just:
`mkdir build; cmake -Bbuild -H.; cd build; make; cd ..; cp build/darknet .; cp build/libdarknet* .; rm -r build`
Thanks

**Comment by cuongdev** [comment]
> ok so... in the
> `mkdir build; cmake -Bbuild -H.; cd build; make; cd ..; cp build/darknet .; rm -r build`
> the issue is last command:
> `rm -r build`
> because in build folder there is darknet binary and your missing lib/file as well...
> do please do not remove build, by just:
> `mkdir build; cmake -Bbuild -H.; cd build; make; cd ..; cp build/darknet .; cp build/libdarknet* .; rm -r build`
> Thanks
There's still no libdarknet.so :(

<img width="781" alt="Screen Shot 2019-06-08 at 12 23 40 PM" src="https://user-images.githubusercontent.com/11372981/59142422-4b48f000-89e8-11e9-8fbd-a19dc30d6a39.png">

**Comment by sowson** [comment]
on macOS there is no so lib only on Linux... on macos you have "a"(static lib) and "dynlib" (dynamic one)... so change to the one of them in your python script :D. I am not sure which one... sorry I do not know the python at all ;/.

**Comment by cuongdev** [comment]
> on macOS there is no so lib only on Linux... on macos you have "a"(static lib) and "dynlib" (dynamic one)... so change to the one of them in your python script :D. I am not sure which one... sorry I do not know the python at all ;/.

I will try to implement using static lib. Thank you so much for helping me.

**Comment by yaoanderson** [comment]
Hi @cuongdev,
I can share you mine in Mac  : )
[libdarknet.so txt](https://github.com/sowson/darknet/files/3268225/libdarknet.so.txt)

**Comment by cuongdev** [comment]
> Hi @cuongdev,
> I can share you mine in Mac : )
> [libdarknet.so txt](https://github.com/sowson/darknet/files/3268225/libdarknet.so.txt)

How did you compile that file?
I tried to use your file but it got some errors
<img width="781" alt="Screen Shot 2019-06-08 at 12 23 40 PM" src="https://user-images.githubusercontent.com/11372981/59142644-5cdfc700-89eb-11e9-801e-ac1d11c24412.png">

**Comment by sowson** [comment]
Did you try dynlib instead of so? I red about it and dynlib seams to be used on macOS... but in absolute path... let me know is that still an issue?
