### ISSUE TITLE
Bounding box incorrect with tiny YOLO v3

### ISSUE THREAD

**Issue by yashhema** [sowson/darknet#19]
Hello, I ran a detection with a pretrained model with default tiny YOLO v3 . The input photo is of width 640 and length 320.
The detection was correct ie all objects were rightly detected but bounding boxes were wrong.
Can you please give me any suggestions, what can be the issue

**Comment by sowson** [comment]
Hi @yashhema if you provide me detailed test method step by step I can double check all algorithms and try to help you best I can. Thanks!
