### ISSUE TITLE
Issue when creating the file at the _make_ command

### ISSUE THREAD

**Issue by pgarhwal** [sowson/darknet#22]
Hey, I have been running into an issue when I am creating the darknet executable file. I am on macOS Catalina. The python version is 3.7.6 . When I try to run the _make -j8_ command after running the _cmake_ command, I run into the following error.

<img width="1259" alt="Screenshot 2020-01-27 at 3 46 26 PM" src="https://user-images.githubusercontent.com/24452328/73166703-5e960080-411c-11ea-8873-887ebf9c6ab7.png">

If you need any more information, I am happy to provide it. 

Thanks

**Comment by sowson** [comment]
Hi, have you checked the https://codingbytodesign.net/2018/05/26/darknet-training/ macOS command sequence is provided there. I checked and it should works :D.

**Comment by sowson** [comment]
btw, looks like you do not have OpenCV installed.

**Comment by pgarhwal** [comment]
Hey, 
I followed the steps provided in the link and managed to build darknet with no issues. 

Thanks @sowson , I was worried about darknet not running on a Mac and was about to install VirtualBox to run it on another OS. I'll close the issue now, thanks again.
