### ISSUE TITLE
Save model after 1000 iterations

### ISSUE THREAD

**Issue by devlakshmi** [sowson/darknet#27]
Hi @sowson ,
I want to save the model every 1000 iterations, now model gets saved in 100 th to 900 th iterations after that it is not. I didnt detector.c , pls guide me with this issue

**Comment by sowson** [comment]
In the CFG file, you should have steps variable that you can change to do so... I hope it helps. Thanks for this issue! Any issue brings me some lesson, hope I will get more like this. ;-).

**Comment by sowson** [comment]
Look into the code in the examples/detector.c and change!
