### ISSUE TITLE
rebase work

### ISSUE THREAD

**Issue by cenit** [sowson/darknet#28]
Hi! Thanks for your wonderful work enabling OpenCL for darknet.
Any possibility that you rebase your work on the https://github.com/AlexeyAB/darknet fork? It is much more maintained, it will be (maybe) the reference darknet implementation now that the pjreddie original one points to that and also there is a huge chance that your work might be accepted upstream!

**Comment by sowson** [comment]
I am sorry but I do not have time to do it... sorry.
