### ISSUE TITLE
YoloV4

### ISSUE THREAD

**Issue by runaway** [sowson/darknet#29]
Can the project support YoloV4 training?

**Comment by sowson** [comment]
Not yet...

**Comment by maitheen** [comment]
Do you have OpenCL code for Yolo4

**Comment by sowson** [comment]
I am working on this but not wanted to share it just yet. Thanks!

**Comment by maitheen** [comment]
Dear Sowson,
Thank you so much for your reply.
This is Maitheen Farmannulla and I’m an international student in National
Cheng Kung University, Taiwan.
Right now, I’m pursuing my master's in Computer Science and Information
Engineering.
My project is about YOLO v4 and I have to implement it in our Computer
Architecture and System Laboratory, Graphics Processing Unit.
My senior implemented the YOLO v3 in our laboratory GPU and he used your
link to implement it. https://github.com/sowson/darknet.
My senior referred your link to me. That’s why I asked you about YOLO v4
OpenCL.
As an international student, I need to complete my master's within two
years and this is my final year, so I have to complete my project as soon
as possible. If I have the OpenCL code for YOLO v4 I can able to implement
it in my lab GPU. I humbly request you to help me with this.
Thank you.

**Comment by sowson** [comment]
Hello @runaway @maitheen,

I committed the version with YOLO4 experimental support, not all are working yet, I am deep dive into issues. The issue was to separate YOLO4 from previous work parts. So pls use an [yolo4] instead of [yolo] in YOLO4 CFG files. And all pull requests are welcome if you find issues. It is difficult to time for me to make it better. The last thing in the project "cfg" folder is ready to reuse models.

Thanks!

**Comment by maitheen** [comment]
Dear Sowson,

Firstly, I would like to thank you with my whole heart and

I am so happy that you have given your importance to me regarding this YOLO
v4.

I am really blessed to see such a renowned scientist like you.

You have become my life's turning point.

I will never forget you in my entire life and you mean a lot to me.

I always expect positive gestures and reply from your side.

Once again, thank you for helping me with my thesis.

Thank you.

**Comment by sowson** [comment]
@maitheen I am not so smart, but anyway happy to read what you wrote. Anyway, I have still a stability issue. Pls wait few more days or use CPU only flags till I stabilize the training process of YOLO4 in OpenCL. Thanks!

**Comment by sowson** [comment]
@maitheen I have an interesting idea for your master thesis, pls use the YOLO3 model, but replace inside [yolo] to [yolo4] it will be an interesting change, also you may change activation functions to MISH, that should be super stable for training, so you will not use a full YOLO4 but some elements of this model... works for you? :-).

**Comment by sowson** [comment]
@maitheen I finished YOLO4 elements port for now... Good Luck!

**Comment by maitheen** [comment]
Dear Sowson,
Thank you so much for your motivation and it's happy to hear that you have
completed YOLO v4.
I'll start my work, if any doubts arise I'll let you know and please be
there for me in all aspects.
Thank You.

**Comment by sowson** [comment]
![Screen Shot 2020-10-02 at 12 05 19 PM](https://user-images.githubusercontent.com/33941184/94912724-61fe3a80-04a8-11eb-9e58-0fa0c9e72cd0.png)
:D all solved! :D... training too... :D.

**Comment by maitheen** [comment]
[image: Screenshot from 2020-10-05 19-29-52.png]
Dear Sowson,
From the morning I'm trying to resolve the error, but I can't I don't know
whether it is my mistake in the installation or some coding error.
Could you please clarify it.
Thank you

**Comment by sowson** [comment]
Hey, @maitheen I cannot see your screenshot.

**Comment by maitheen** [comment]
Dear Sowson,
Please check through this link.
Thank you.
https://drive.google.com/drive/folders/1aKt8ANSkJpchgJppHepsN68YgAzwc9wK?usp=sharing

**Comment by sowson** [comment]
are you unable to read? :p

**Comment by maitheen** [comment]
What do you mean, I did not understand could you please tell briefly.

**Comment by sowson** [comment]
read what error said!

**Comment by maitheen** [comment]
I read the error, I already installed OpenCV-2.4.13.5.
But I don't know why the error occurred.

**Comment by sowson** [comment]
Are you sure? devel version (headers and other things)? is it ubuntu?

**Comment by sowson** [comment]
In ubuntu name of the correct package is: libopencv-dev

**Comment by sowson** [comment]
btw, what gpu(s) you have? wonder how fast drivers in ubuntu work? pls help on that to me... I tried 18.04 and drivers for Radeon VII gpus were very very slow

**Comment by maitheen** [comment]
yes, I'm sure and it is ubuntu.
you can also check the link, I have attached the screenshot in that you can
see the OpenCV which I installed.

https://drive.google.com/drive/folders/1aKt8ANSkJpchgJppHepsN68YgAzwc9wK?usp=sharing

**Comment by sowson** [comment]
hmm... why you do not use?: sudo apt install libopencv-dev

**Comment by sowson** [comment]
same for libomp-dev etc...

**Comment by sowson** [comment]
and regarding GPU(s) what you have?

**Comment by maitheen** [comment]
Till now I'm using my CPU to run the OpenCL, In my CPU I don't have any GPU
once I achieved the results on my computer.
Then I will use Nvidia GPU.
The below image is the GPU which I'm going to use.
[image: GPU NAME.png]

**Comment by maitheen** [comment]
I already did sudo apt install libopencv-dev, but it's not working.
you can also see that in the below image and also I have attached in the
google drive link.
[image: sudo.png]

**Comment by sowson** [comment]
you have to figure out how to use OpenCV v2 or v3 because v4 it is not supported...

**Comment by sowson** [comment]
Try this... https://www.learnopencv.com/install-opencv-3-4-4-on-ubuntu-18-04/ :P

**Comment by maitheen** [comment]
[image: Tried to GPU .png]

While I tried to compile in my GPU, this error was occurring.
It shows the clBLas is missing.
You can see the error in the above image

**Comment by sowson** [comment]
use: sudo apt install libclblas-dev
if you have an multi GPU isse (not enable in Makefile! keep disabled!) use https://github.com/sowson/clBLAS and replace clBLAS..2.12.0.so
thx!

**Comment by sowson** [comment]
sorry but again cannot see image you added

**Comment by maitheen** [comment]
You can check the link to see the error.

https://drive.google.com/file/d/1SdqTofUQkNA0X10k6xk69UvEjZ60naei/view?usp=sharing

**Comment by maitheen** [comment]
Okay,  I'll try this now.

**Comment by sowson** [comment]
I think nothing more needs to be added here. Thanks!
