### ISSUE TITLE
Error when compile on MacBook Pro 2019

### ISSUE THREAD

**Issue by nguyentrong56** [sowson/darknet#31]
Hello,
I tried to run make but it give me this error :
ld: warning: directory not found for option '-L/usr/lib/x86_64-linux-gnu/'
ld: warning: directory not found for option '-L/usr/lib64'
ld: library not found for -lOpenCL
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libdarknet.so] Error 1
Please advise 
Thanks

**Comment by hooping** [comment]
@nguyentrong56 
Would you post your Makefile? It seems you changed the AMD=1 in the Makefile, right? 
I am also working on Macbook Pro 2019.

Find the content below 
"ifeq ($(AMD), 1)
COMMON+= -DGPU -DOPENCL
CFLAGS+= -DGPU -DOPENCL -I/usr/include/
**LDFLAGS+= -L/usr/lib/x86_64-linux-gnu/ -lOpenCL -lclBLAS**
LDFLAGS+= -L/usr/lib64
endif"

Change the lines in bold, there is no error, but not sure if it works...
"ifeq ($(AMD), 1)
COMMON+= -DGPU -DOPENCL
CFLAGS+= -DGPU -DOPENCL -I/usr/include/
**LDFLAGS+= -L/usr/lib/x86_64-linux-gnu/ -framework OpenCL -lclBLAS**
LDFLAGS+= -L/usr/lib64
endif"

**Comment by sowson** [comment]
# BREW
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# OpenCV2
brew install opencv@2
brew link --force opencv@2
# OpenCV3 (if you do not want OpenCV2)
brew install opencv@3
brew link --force opencv@3
# Rest Dependencies and Build (CMAKE!)
brew install libomp
brew install clblas
brew install clfft
brew install cmake
brew install wget
mkdir github; cd github; git clone https://github.com/sowson/darknet.git
cd darknet; mkdir build; cmake -Bbuild -H.; cd build; make; cd ..; cp build/darknet .; rm -r build

**Comment by sowson** [comment]
@nguyentrong56 can we close this issue?

**Comment by sowson** [comment]
No comments yet, so I am closing it. Thx!
