### ISSUE TITLE
Support for camera

### ISSUE THREAD

**Issue by road2programmer** [sowson/darknet#44]
Hello,
I have built the binary using OpenCV 3.4.11 and it works. However, if I try to use the camera (./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights) the application starts to not respond... it takes a while to load the image, but once loaded, the image displayed never changes although the graphics card is being used. Also, when I try to use a video as an input, I get floating point exception...

Have problems like those happened to someone? Maybe the camera problems are because of low fps (I tested and had like 13fps which is super low... but when using the app I get 1fps and I do not know why), also... any ideas about the floating point exception when trying to process video inputs?

Thank you a lot

**Comment by sowson** [comment]
well I am doing this in darknet folder:

`./darknet detector demo cfg/coco.data cfg/yolov3.cfg ../../../weights/yolov3.weights -c 0 -i 0`

I got 13 fps, do not know what is issue with your setup, sorry :).

**Comment by sowson** [comment]
no comments... seems the issue can be closed... feel free to reopen...
