### ISSUE TITLE
Errors when compile the project: undefined reference to 'avg_predictions'

### ISSUE THREAD

**Issue by trriger** [sowson/darknet#45]
When I try to compile this project on Ubuntu18.04.  It goes wrong and show the error--- **undefined reference to 'avg_predictions'**, which is shown as following:
![image](https://user-images.githubusercontent.com/55041272/114295540-6ef38a80-9ad8-11eb-8e01-6724cfded522.png)

@sowson How to fix it?

**Comment by TaihuLight** [comment]
(1) The function ```detection *avg_predictions(network *net, int *nboxes)``` is old and should be instead with the new function ```get_network_boxes```. Thus, In the file examples/yolo.c, you should fix the code with the method shown as following.
	// replace this
        //dets = avg_predictions(&net, &nboxes);
	dets = get_network_boxes(&net, 1, 1, thresh, 0, 0, 0, &nboxes);

(2) The width of line in detected boxes is too small to be seen for several images. Therefore, 

//int width = im.h * .001;
int width = im.h * .005;
