### ISSUE TITLE
opencl gemm_kernel error: CL_INVALID_WORK_GROUP_SIZE  for the function gemm_offset_gpu() in blas_kernels.c

### ISSUE THREAD

**Issue by TaihuLight** [sowson/darknet#46]
When I run darknet using the function gemm_offset_gpu() in blas_kernels.c, it occurs the following error:
`FATAL ERROR: CL_INVALID_WORK_GROUP_SIZE
opencl gemm_kernel error: CL_INVALID_WORK_GROUP_SIZE`

How to fix it?

**Comment by sowson** [comment]
Yes, I was trying to dynamically adjust tuning parameters (in 7 methods) but I decided to put it as a const. pls try to re-clone now and build. thanks! :).

**Comment by sowson** [comment]
Hi, is it anything better now?

**Comment by sowson** [comment]
no comments... seems the issue can be closed... feel free to reopen...

**Comment by ziqi-zhang** [comment]
Hi @sowson , I cloned the code two or three weeks ago but I got the same problem ``FATAL ERROR: CL_INVALID_WORK_GROUP_SIZE opencl gemm_kernel error: CL_INVALID_WORK_GROUP_SIZE``. It seems that the problem is not solved?
