### ISSUE TITLE
Running Issue Error

### ISSUE THREAD

**Issue by kchpomp** [sowson/darknet#49]
Hello!
I've faced with several problems, I've already left a comment under your post on your website. 
I use BeagleBone AI and have my own trained YOLOv4 model. I've instaled Darknet in OpenCL as in your guide.
Then I try to run the detection using following command : ./darknet detector demo cfg/obj.data cfg/yolov4-obj.cfg /weights/yolov4.weights video1.mp4
And CCL shows the following respond: TIOCL WARNING: Opening Linux shared memory: No such file or Directory.
TIOCL FATAL: The TI Multicore Tools daemon (/usr/bin/ti-mctd) is not running. To start daemon, rm /dev/shm/HeapManager (if exists); ti-mctd. Re-run application. Refer User Guide for details. Aborted.

Don't know what is happening and how to fix this problem. Can you explain/help me to solve this problem??

**Comment by sowson** [comment]
sorry to say I did not succeed with the beagle board yet... any idea or finding I would appreciate, but I have no idea what is working here? sorry :).

**Comment by kchpomp** [comment]
> sorry to say I did not succeed with the beagle board yet... any idea or finding I would appreciate, but I have no idea what is working here? sorry :).

Actually, I tried, however still didn't find answer. Can you please answer. I used your guide https://iblog.isowa.io/2020/04/29/darknet-in-opencl-on-beagleboard-ai/ . I have several questions:
1.What OS you have on BeagleBone AI ?
2. You installed it directly on eMMC or you use it on SD Card?
3. Have you got HeapManager file in /dev/shm/ directory?
4. Are there any files in /dev/shm directory, because mine is empty.

**Comment by sowson** [comment]
no comments... seems the issue can be closed... feel free to reopen...
