### ISSUE TITLE
Is it applicable for opencl 1.1?

### ISSUE THREAD

**Issue by KurtKoo** [sowson/darknet#51]
I read the blog in which the opencl darknet runs on the beagleboard. 
And I want to deploy the opencl darknet on the TI product, TMDSEVM572X. The opencl 1.1 is installed on the board.
According to the blog, should I just make modifications as below?
1. In src/opencl.h file, "#define CL_TARGET_VERSION 110"
2. In Makefile file, "ifeq ($(ARM), 1) " part, COMMON+= -DGPU -DOPENCL -DCL_TARGET_OPENCL_VERSION=110 -DARM

**Comment by sowson** [comment]
the code base is 1.1 really but tested on 1.2+ pls give a try your idea you may succeed :).

**Comment by KurtKoo** [comment]
Thank you! I'll give some feedback as soon as I test on the board.

**Comment by sowson** [comment]
no comments... seems the issue can be closed... feel free to reopen...
