### ISSUE TITLE
Error while loading shared libraries: libclBLAS.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by MAMorgado** [sowson/darknet#53]
Hello Piotr,

I'm trying to use your program as a replacement for the traditional Darknet with OpenCV and CUDA since I don't have the hardware necessary for running CUDA. It is a much appreciated project.

I'm using Ubuntu 20.04 and OpenCL version 4.5.3.

I compiled it without problems (make), and I was about to test it with my webcam. Do we use the same commands as darknet? For example to start your version of darknet for webcam in real time it would be ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights in the darknet directory?

I downlaoded the coco data set using the script, and tried to install clBLAS using the instructions in the makefile.

However when I try to run it I'm getting the following error:
./darknet: error while loading shared libraries: libclBLAS.so.2: cannot open shared object file: No such file or directory

Do you know why is this and what can I do to fix it? 

If I'm not running it wrongly I think it may be the instalation of libcIBLAS because I got these messages when trying to download them:

darknet/clBLAS-2.12.0-Linux-x64$ sudo cp lib64/* /usr/lib64/
cp: -r not specified; omitting directory 'lib64/cmake'
cp: -r not specified; omitting directory 'lib64/pkgconfig'

darknet/clBLAS-2.12.0-Linux-x64$ sudo cp lib64/* /usr/lib64/
cp: -r not specified; omitting directory 'lib64/cmake'
cp: -r not specified; omitting directory 'lib64/pkgconfig'

darknet/clBLAS-2.12.0-Linux-x64$ sudo cp -r lib64/cmake/* /usr/lib64/cmake/
husarion@vdisrobot2:~/husarion_ws/src/darknetmod/darknet/clBLAS-2.12.0-Linux-x64$ sudo cp -r lib64/pkgconfig/* /usr/lib64/pkgconfig/
cp: cannot create regular file '/usr/lib64/pkgconfig/': Not a directory

I would appreciate any help you might be able to give me,

Best regards,

MaM

**Comment by MAMorgado** [comment]
My bad! I had the wrong GPU setting. I don't have this problem anymore

**Comment by Deblazz** [comment]
Hi, I have the same error, could you please tell me how you fixed it?
